// through parallel.Invoke()


static void methodA()
        {
            throw new Exception("method A Exception");
        }
        static void methodB()
        {
            throw new Exception("method B Exception");
        }
        static void methodC()
        {
            throw new Exception("method C Exception");
        }

        static void Main(string[] args)
        {
            try
            {
                Parallel.Invoke(new Action[] { methodA , methodB , methodC });
            }
            catch(AggregateException ex)
            {
                foreach(var n in ex.InnerExceptions)
                {
                    Console.WriteLine(n.Message);
                }
            }
        }